### ISSUE TITLE
misc/tools: add a scrip to create and update index.md

### ISSUE THREAD

**Issue by sarathsp06** [sarathsp06/ctci#2]
Index file has to be a markdown file that may work as the index for all the problems in the repo. 

It could be manually created every new problem push or generated using a tool. Would like suggestions

**Comment by arjunmahishi** [comment]
Why index.md? can the index not be in the readme.md itself?

**Comment by arjunmahishi** [comment]
Addressed this in #24. Only thing is, we will need to maintain separate folders for each problem

**Comment by sarathsp06** [comment]
@arjunmahishi wanted index.md just so that the file is completely autogenerated , thanks  for the PR will review ASAP

**Comment by arjunmahishi** [comment]
We can still have the CTCI questions in individual files right? Since there are limited question, maybe we can just generate files for all the questions at the beginning itself. Then we can add code inside with whichever language(s).

**Comment by sarathsp06** [comment]
@arjunmahishi  That sounds like a good idea , it would be nice to show a smily like ⚠️ , 💯 , 🔰  etc  indicating status of the problem

**Comment by arjunmahishi** [comment]
> @arjunmahishi wanted index.md just so that the file is completely autogenerated

We can still generate an index part and paste it on some kind of a `README.md` template. The advantage of this is, github-pages can be used.
